FROM python:3.11-slim
WORKDIR /app


# system deps for some drivers (if needed)
RUN apt-get update && apt-get install -y build-essential default-libmysqlclient-dev && rm -rf /var/lib/apt/lists/*


COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


COPY . .
EXPOSE 5000
CMD ["python", "app.py"]
